apiVersion: v1
kind: Service
metadata:
  name: postgres-ledger
  namespace: payment
spec:
  selector:
    app: postgres-ledger
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-ledger
  namespace: payment
spec:
  serviceName: postgres-ledger
  replicas: 1
  selector:
    matchLabels:
      app: postgres-ledger
  template:
    metadata:
      labels:
        app: postgres-ledger
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: LedgerService
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
