apiVersion: v1
kind: Service
metadata:
  name: settlement-service
  namespace: payment
spec:
  selector:
    app: settlement-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: settlement-service
  namespace: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: settlement-service
  template:
    metadata:
      labels:
        app: settlement-service
    spec:
      containers:
        - name: settlement-service
          image: localhost:5000/payment-settlement-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SERVER_PORT
              value: "8082"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-settlement:5432/SettlementService?sslmode=disable&preferQueryMode=simple"
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: NIBSS_TIMEOUT_MS
              value: "5000"
            - name: NIBSS_MOCK_FAIL_RATE
              value: "0.2"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
