spring.application.name=payment-service
server.port=8080

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/PaymentService?sslmode=disable&preferQueryMode=simple
spring.datasource.username=postgres
spring.datasource.password=Bolu@123wat$ife
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=35
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.leak-detection-threshold=5000
spring.datasource.hikari.data-source-properties.prepareThreshold=5

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Feign + Circuit Breaker
feign.circuitbreaker.enabled=true

# Feign clients
ledger-service.url=http://localhost:8081
settlement-service.url=http://localhost:8082

# Actuator / Prometheus
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

# Resilience4j Circuit Breaker for Feign clients
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=15s
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.ledgerClient.baseConfig=default
resilience4j.circuitbreaker.instances.settlementClient.baseConfig=default

# Resilience4j Retry
resilience4j.retry.configs.default.maxAttempts=3
resilience4j.retry.configs.default.waitDuration=500
resilience4j.retry.configs.default.exponentialBackoffMultiplier=2
resilience4j.retry.instances.ledgerClient.baseConfig=default
resilience4j.retry.instances.settlementClient.baseConfig=default

# Resilience4j TimeLimiter
resilience4j.timelimiter.configs.default.timeoutDuration=5s
resilience4j.timelimiter.instances.ledgerClient.baseConfig=default
resilience4j.timelimiter.instances.settlementClient.baseConfig=

#debug=true

# Distributed Tracing
management.tracing.sampling.probability=1.0
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] --- [%15.15t] %-40.40logger{39} : %m%n%wEx
